# Generated by Django 5.2.7 on 2025-11-29 19:00
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriber",
            name="last_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscriber",
            name="source",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="subscriber",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("unsubscribed", "Unsubscribed"),
                ],
                default="active",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="context",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="subject",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
