# Generated by Django 5.2.7 on 2025-11-29 20:05
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_extend_subscriber_contactmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="lead_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("normal", "Normal"), ("hot", "Hot")],
                default="normal",
                max_length=12,
            ),
        ),
    ]
